Repository metron-labs/secrets-manager-old, pull requests merged in 2025-03, with the labels that each got.

#23 Keep 145 oci python develop
  sdk/javascript/packages/oracle/package-lock.json
  sdk/python/storage/keeper_secrets_manager_storage/storage_oci_key_management/README.md
  sdk/python/storage/keeper_secrets_manager_storage/storage_oci_key_management/__init__.py
  sdk/python/storage/keeper_secrets_manager_storage/storage_oci_key_management/constants.py
  sdk/python/storage/keeper_secrets_manager_storage/storage_oci_key_management/oci_kms_client.py
  sdk/python/storage/keeper_secrets_manager_storage/storage_oci_key_management/oci_session_config.py
  sdk/python/storage/keeper_secrets_manager_storage/storage_oci_key_management/oracle_key_value_storage.py
  sdk/python/storage/keeper_secrets_manager_storage/storage_oci_key_management/requirements_oci.txt
  sdk/python/storage/keeper_secrets_manager_storage/storage_oci_key_management/utils.py
Labels: Python

#38 Keep 159 azurekv dotnet
  sdk/dotNet/Integrations/AzureKeyVault/.gitignore
  sdk/dotNet/Integrations/AzureKeyVault/AzureKeyValueStorage.cs
  sdk/dotNet/Integrations/AzureKeyVault/AzureKeyVault.csproj
  sdk/dotNet/Integrations/AzureKeyVault/AzureKeyVault.sln
  sdk/dotNet/Integrations/AzureKeyVault/AzureSessionConfig.cs
  sdk/dotNet/Integrations/AzureKeyVault/README.md
  sdk/dotNet/Integrations/AzureKeyVault/constants.cs
  sdk/dotNet/Integrations/AzureKeyVault/utils.cs
Labels: c#

#36 KEEP-161 aws dotnet integration
  sdk/dotNet/Integrations/AWSKeyManagement/.gitignore
  sdk/dotNet/Integrations/AWSKeyManagement/AWSKMSClient.cs
  sdk/dotNet/Integrations/AWSKeyManagement/AWSKeyManagement.csproj
  sdk/dotNet/Integrations/AWSKeyManagement/AWSKeyManagement.sln
  sdk/dotNet/Integrations/AWSKeyManagement/AWSKeyValueStorage.cs
  sdk/dotNet/Integrations/AWSKeyManagement/AWSSessionConfig.cs
  sdk/dotNet/Integrations/AWSKeyManagement/README.md
  sdk/dotNet/Integrations/AWSKeyManagement/constants.cs
  sdk/dotNet/Integrations/AWSKeyManagement/utils.cs
Labels: c#

#37 Keep 160 gcp dotnet
  sdk/dotNet/Integrations/GCPKeyManagement/.gitignore
  sdk/dotNet/Integrations/GCPKeyManagement/GCPKeyConfig.cs
  sdk/dotNet/Integrations/GCPKeyManagement/GCPKeyManagement.csproj
  sdk/dotNet/Integrations/GCPKeyManagement/GCPKeyManagement.sln
  sdk/dotNet/Integrations/GCPKeyManagement/GCPKeyValueStorage.cs
  sdk/dotNet/Integrations/GCPKeyManagement/GCPKeyVaultClient.cs
  sdk/dotNet/Integrations/GCPKeyManagement/README.md
  sdk/dotNet/Integrations/GCPKeyManagement/constants.cs
  sdk/dotNet/Integrations/GCPKeyManagement/utils.cs
Labels: c#

#35 KEEP-162 dotnet oracle key vault integration
  sdk/dotNet/Integrations/OracleKeyManagement/.gitignore
  sdk/dotNet/Integrations/OracleKeyManagement/OracleKeyManagement.csproj
  sdk/dotNet/Integrations/OracleKeyManagement/OracleKeyManagement.sln
  sdk/dotNet/Integrations/OracleKeyManagement/OracleKeyValueStorage.cs
  sdk/dotNet/Integrations/OracleKeyManagement/OracleKmsClient.cs
  sdk/dotNet/Integrations/OracleKeyManagement/OracleSessionConfig.cs
  sdk/dotNet/Integrations/OracleKeyManagement/README.md
  sdk/dotNet/Integrations/OracleKeyManagement/constants.cs
  sdk/dotNet/Integrations/OracleKeyManagement/utils.cs
Labels: c#

#19 Keep-143 Initial commit aws-java sdk integartion
  sdk/java/aws/.gitignore
  sdk/java/aws/README.md
  sdk/java/aws/build.gradle.kts
  sdk/java/aws/gradle/libs.versions.toml
  sdk/java/aws/gradle/wrapper/gradle-wrapper.jar
  sdk/java/aws/gradle/wrapper/gradle-wrapper.properties
  sdk/java/aws/settings.gradle.kts
  sdk/java/aws/src/main/java/com/keepersecurity/secretmanager/aws/kms/AWSKMSClient.java
  sdk/java/aws/src/main/java/com/keepersecurity/secretmanager/aws/kms/AwsKeyValueStorage.java
  sdk/java/aws/src/main/java/com/keepersecurity/secretmanager/aws/kms/AwsSessionConfig.java
  sdk/java/aws/src/main/java/com/keepersecurity/secretmanager/aws/kms/Constants.java
  sdk/java/aws/src/main/java/com/keepersecurity/secretmanager/aws/kms/JsonUtil.java
  sdk/java/aws/src/main/resources/logback.xml
Labels: Java

#12 Keep- 138 Azure- Java-develop_internal_PR
  .gitignore
  sdk/java/azure/README.md
  sdk/java/azure/build.gradle.kts
  sdk/java/azure/gradle/libs.versions.toml
  sdk/java/azure/gradle/wrapper/gradle-wrapper.jar
  sdk/java/azure/gradle/wrapper/gradle-wrapper.properties
  sdk/java/azure/settings.gradle.kts
  sdk/java/azure/src/main/java/com/keepersecurity/secretmanager/azurekv/AzureKeyValueStorage.java
  sdk/java/azure/src/main/java/com/keepersecurity/secretmanager/azurekv/AzureSessionConfig.java
  sdk/java/azure/src/main/java/com/keepersecurity/secretmanager/azurekv/Constants.java
  sdk/java/azure/src/main/java/com/keepersecurity/secretmanager/azurekv/JsonUtils.java
  sdk/java/azure/src/main/resources/logback.xml
Labels: Java
